MIN_THICKNESS = 1
MAX_THICKNESS = 20
STR_THICKNESS = f'Минимальная толщина - {MIN_THICKNESS}, максимальная - {MAX_THICKNESS}'
INPUT_THICKNESS = 'Введите толщину'
INPUT_IMAGE = 'Выбрать картинку'
NAME_DB = 'action_log_db.sqlite'
ID = 'id'
ACTION = 'action'
IS_DELETED = 'is_deleted'
ACTIONS = 'actions'
LOG = 'log'
BRUSH = 'Brush'
LINE = 'Line'
CIRCLE = 'Circle'
RECTANGLE = 'Rectangle'
ERASER = 'Eraser'
NUM_ACTION = 1
NUM_SX = 2
NUM_SY = 3
NUM_EX = 4
NUM_EY = 5
NUM_RED = 6
NUM_GREEN = 7
NUM_BLUE = 8
NUM_THICKNESS = 9