# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(469, 197)
        self.lbl = QtWidgets.QLabel(Form)
        self.lbl.setGeometry(QtCore.QRect(20, 20, 251, 16))
        self.lbl.setObjectName("lbl")
        self.radio_btn_yes = QtWidgets.QRadioButton(Form)
        self.radio_btn_yes.setGeometry(QtCore.QRect(20, 90, 281, 20))
        self.radio_btn_yes.setChecked(True)
        self.radio_btn_yes.setObjectName("radio_btn_yes")
        self.radio_btn_no = QtWidgets.QRadioButton(Form)
        self.radio_btn_no.setGeometry(QtCore.QRect(20, 120, 311, 20))
        self.radio_btn_no.setChecked(False)
        self.radio_btn_no.setObjectName("radio_btn_no")
        self.btn_ok = QtWidgets.QPushButton(Form)
        self.btn_ok.setGeometry(QtCore.QRect(340, 160, 93, 28))
        self.btn_ok.setObjectName("btn_ok")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 50, 451, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Загрузить предыдущую работу "))
        self.lbl.setText(_translate("Form", "Вы хотите загрузить предыдущую работу?"))
        self.radio_btn_yes.setText(_translate("Form", "Да, я хочу загрузить предыдущую работу."))
        self.radio_btn_no.setText(_translate("Form", "Нет, я не хочу загружать предыдущую работу."))
        self.btn_ok.setText(_translate("Form", "OK"))
        self.label.setText(_translate("Form", "Если вы не загружете предыдущую работу, она будет потеряна навсегда."))
